import { Box, Container } from "@mui/material";
import Head from "next/head";
import React from "react";

import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* 아래와 같이 MUI 컴포넌트를 불러와서 사용한다 */}
      <Container maxWidth="sm">
        <Box
          sx={{
            width: 300,
            height: 300,
            backgroundColor: "primary.dark",
            "&:hover": {
              backgroundColor: "primary.main",
              opacity: [0.9, 0.8, 0.7],
            },
          }}
        />
      </Container>
    </div>
  );
}
